# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gianluca Della Vedova
tagline:          ''
description:      ''
url:              https://gianluca.dellavedova.org
baseurl:          /

author:
  name:           'Mark Otto'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
