# Site settings
title: Gianluca Della Vedova
description: >- # this means to ignore newlines until "baseurl:"
  My home page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gianluca.dellavedova.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
#   #############################à

author:
  name: Gianluca Della Vedova
  email: gianluca@dellavedova.org

# Top menu
header_pages:
  - index.md
  - didattica.md
  - blog.md

rss: rss
feed:
    path: atom.xml

minima:
  skin: auto
  date_format: "%d-%m-%Y"
  # generate social links in footer
  #  social_links:
  #    github:  gdv
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
