baseURL = "https://gianluca.dellavedova.org/"
languageCode = "en-us"
title = "Gianluca Della Vedova"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Gianluca Della Vedova"
    githubUsername = "gdv"
    accent = "darkcyan"
    showBorder = true
    backgroundColor = "white"
    font = "Optima"
    highlight = true
    highlightStyle = "default"
    highlightLanguages = []

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "https://www.unimib.it/gianluca-della-vedova"
    name = "Didattica"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.


# [[menu.icon]]
# url = "mailto:gianluca@dellavedova.org"
# name = "fas fa-envelope"
# weight = 1

# [[menu.icon]]
# url = "https://github.com/gdv/"
# name = "fab fa-github"
# weight = 2
