baseurl: "https://gianluca.dellavedova.org/"
title:  "Gianluca Della Vedova"
languageCode: "en-us"
title: "Gianluca Della Vedova"
theme: "hugo-xmin"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: Blog
      url: "/post/"
      weight: 2
    - name: Didattica
      url: "https://www.unimib.it/gianluca-della-vedova"
      weight: 3
    - name: Subscribe
      url: "index.xml"

params:
  description: "Gianluca Della Vedova."
  footer: "&copy; [Gianluca Della Vedova](https://gianluca.dellavedova.org) 2017 -- {Year} | [Github](https://github.com/gdv) "

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true

